variables:
  - &golang 'golang:1.21@sha256:24a09375a6216764a3eda6a25490a88ac178b5fcb9511d59d0da5ebf9e496474'

steps:
  lint:
    group: test
    image: *golang
    commands:
      - make vet
      - make formatcheck

  test:
    group: test
    image: *golang
    commands:
      - make test

  version:
    image: *golang
    commands:
      - make version

  build-dryrun:
    image: woodpeckerci/plugin-docker-buildx:2.2.0@sha256:6e95efac78f04d45c4177c07489bc01cb6dc5ae6b39f723edd42d5d695b6f2be
    settings:
      repo: woodpeckerci/plugin-github-release
      dockerfile: Dockerfile.multiarch
      dry_run: true
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tags: test
    when:
      event: pull_request

  build-next:
    image: woodpeckerci/plugin-docker-buildx:2.2.0@sha256:6e95efac78f04d45c4177c07489bc01cb6dc5ae6b39f723edd42d5d695b6f2be
    settings:
      repo: woodpeckerci/plugin-github-release
      dockerfile: Dockerfile.multiarch
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tags: next
    secrets: [docker_username, docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  build-tag:
    image: woodpeckerci/plugin-docker-buildx:2.2.0@sha256:6e95efac78f04d45c4177c07489bc01cb6dc5ae6b39f723edd42d5d695b6f2be
    settings:
      repo: woodpeckerci/plugin-github-release
      dockerfile: Dockerfile.multiarch
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tags: [latest, "${CI_COMMIT_TAG##v}"]
    secrets: [docker_username, docker_password]
    when:
      event: tag
