variables:
  - &golang 'golang:1.22'
  - &docker_buildx 'woodpeckerci/plugin-docker-buildx:3.2.1'

steps:
  lint:
    image: *golang
    commands:
      - make vet
      - make formatcheck
    when:
      - event: pull_request
      - event: push
        branch: renovate/*

  test:
    image: *golang
    commands:
      - make test
    when:
      - event: pull_request
      - event: push
        branch: renovate/*

  build-dryrun:
    image: *docker_buildx
    depends_on: [lint, test]
    settings:
      repo: woodpeckerci/plugin-github-release
      dockerfile: Dockerfile.multiarch
      dry_run: true
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tags: test
    when:
      - event: pull_request
      - event: push
        branch: renovate/*

  build-next:
    image: *docker_buildx
    settings:
      repo: woodpeckerci/plugin-github-release
      dockerfile: Dockerfile.multiarch
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tags: next
      username: woodpeckerbot
    secrets: [docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  build-tag:
    image: *docker_buildx
    settings:
      repo: woodpeckerci/plugin-github-release
      dockerfile: Dockerfile.multiarch
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tags: [latest, '${CI_COMMIT_TAG##v}']
      username: woodpeckerbot
    secrets: [docker_password]
    when:
      event: tag
